# Generated by Django 5.1.4 on 2025-01-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0004_blog_alter_amigo_options_alter_familiar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(default='Sin descripción', help_text='Ingrese una descripción del trabajo.', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
